### ISSUE TITLE
An idea for further integration with Clojure world

### ISSUE THREAD

**Issue by jprudent** [TakeoffTech/clj-camel#36]
Hello ! I played a bit with your wrapper. Thank you.
After a while, I was thinking it would be possible to provide a ring integration. The whole `Exchange` class could be translated to Ring datastructure, and we could benefit of the existing ecosystem around Ring. Camel would be a toolbox to create adapters and ports to the outer wild, and the clojure application would abstract from Camel through a ring API. 
What are you thoughts about this ?

**Comment by taraktikos** [comment]
Hello, 
Could you please explain a little bit more? Do you want to have some ring abstraction over camel jetty component?
`from("jetty:http://0.0.0.0:9080/myservice?handlers=securityHandler")` ?
I am trying to understand what problem do you want to solve

**Comment by jprudent** [comment]
Hello @taraktikos 

Sorry for my late response.
I wasn't talking about jetty in particular, I was thinking of using ring for any source / destination camel adapters.
For instance take this one https://camel.apache.org/components/3.4.x/mail-component.html
Most of the data coming from an email through the Exchange class could fit in a [ring request](https://github.com/ring-clojure/ring/wiki/Concepts#requests). It would be more clojuresque.
Moreover, we could benefit of the same abstraction whatever the adapter in use, be it an email or an http request.

I wrote my first message very hastily. Ring is really adapted to the HTTP world and maybe it would be awkward sometimes to fit data in a ring map. But I would be curious to read your thoughts. Anyway I close this issue ;)
